# Generated by Django 4.1.1 on 2022-09-14 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='posts/%Y%M%d')),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('status', models.BooleanField(verbose_name='approved')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
